module.exports = [
    // General / Navigation
    { key: "Search", value: "Search" },
    { key: "Menu", value: "Menu" },
    { key: "MyTasks", value: "My Tasks" },
    { key: "AssignedToMe", value: "Assigned to me" },
    { key: "TodayAndOverdue", value: "Today & Overdue" },
    { key: "Spaces", value: "Spaces" },
    { key: "NewSpace", value: "New Space" },
    { key: "Channels", value: "Channels" },
    { key: "Channel", value: "Channel" },
    { key: "NewChannel", value: "New Channel" },
    { key: "TypeMessage", value: "Type a message..." },
    { key: "NoMessages", value: "No messages yet" },
    { key: "StartConversation", value: "Start the conversation!" },
    { key: "Members", value: "members" },
    { key: "LoadMore", value: "Load more" },
    { key: "Loading", value: "Loading..." },
    { key: "WelcomeBack", value: "Welcome back" },
    { key: "Themes", value: "Themes" },
    { key: "ChooseYourTheme", value: "Choose Your Theme" },
    { key: "ThemeDesc", value: "Customize your interface appearance" },
    { key: "LightMode", value: "Light Mode" },
    { key: "LightModeDesc", value: "Perfect for bright environments and detailed work" },
    { key: "DarkMode", value: "Dark Mode" },
    { key: "DarkModeDesc", value: "Easy on the eyes, perfect for low light conditions" },
    { key: "SaveTheme", value: "Save Theme" },
    { key: "NoChanges", value: "No Changes" },
    { key: "LightModePreview", value: "Light Mode Preview" },
    { key: "DarkModePreview", value: "Dark Mode Preview" },
    { key: "Dashboard", value: "Dashboard" },
    { key: "Calendar", value: "Calendar" },
    { key: "Messages", value: "Messages" },

    // Dashboard
    { key: "ProjectsIntro", value: "Here's what's happening with your projects today" },
    { key: "TotalProjects", value: "Total Projects" },
    { key: "PendingTasks", value: "Pending Tasks" },
    { key: "Completed", value: "Completed" },
    { key: "NoActiveProjects", value: "No active projects" },
    { key: "GetStartedProject", value: "Get started by creating a new project or inviting your team members to collaborate." },
    { key: "CreateNewProject", value: "Create New Project" },
    { key: "LoadingDashboard", value: "Loading dashboard…" },
    { key: "Refresh", value: "Refresh" },
    { key: "TotalTasks", value: "Total Tasks" },
    { key: "InProgress", value: "In Progress" },
    { key: "Overdue", value: "Overdue" },
    { key: "TaskDistribution", value: "Task Distribution" },
    { key: "NoData", value: "No data" },
    { key: "NoOverdueTasks", value: "No overdue tasks!" },
    { key: "YoureOnTrack", value: "You're on track" },
    { key: "MySpaces", value: "My Spaces" },
    { key: "NoSpacesYet", value: "No spaces yet" },
    { key: "DueThisWeek", value: "Due this week" },
    { key: "ByPriority", value: "By priority" },
    { key: "PriorityTasks", value: "Priority Tasks" },
    { key: "Items", value: "Items" },
    { key: "Task", value: "Task" },
    { key: "Tasks", value: "Tasks" },
    { key: "Context", value: "Context" },
    { key: "Due", value: "Due" },
    { key: "NoPriorityTasks", value: "No priority tasks" },
    { key: "CreateTasksHint", value: "Create tasks in your projects to see them here" },
    { key: "RecentActivity", value: "Recent Activity" },
    { key: "On", value: "On" },
    { key: "NoRecentActivity", value: "No recent activity" },
    { key: "QuickActions", value: "Quick Actions" },
    { key: "ViewAllTasks", value: "View All Tasks" },
    { key: "BrowseProjects", value: "Browse Projects" },
    { key: "MyProfile", value: "My Profile" },
    { key: "JustNow", value: "just now" },
    { key: "MinAgo", value: "m ago" },
    { key: "HourAgo", value: "h ago" },
    { key: "DayAgo", value: "d ago" },
    { key: "High", value: "High" },
    { key: "Medium", value: "Medium" },
    { key: "Low", value: "Low" },
    { key: "Urgent", value: "Urgent" },
    { key: "None", value: "None" },
    { key: "NoAssignedTasks", value: "No assigned tasks yet" },
    { key: "NoAssignedTasksHint", value: "Tasks assigned to you will appear here" },
    { key: "DueToday", value: "Due Today" },
    { key: "OverdueDays", value: "{{days}} days overdue" },
    { key: "NoTasksToday", value: "No tasks due today" },
    { key: "NoTasksTodayHint", value: "Great! You're all caught up" },
    { key: "ToDo", value: "To Do" },
    { key: "InProgress", value: "In Progress" },
    { key: "Pending", value: "Pending" },
    { key: "TotalTasks", value: "Total Tasks" },
    { key: "ByPriority", value: "By Priority" },
    { key: "CompletionOverview", value: "Completion Overview" },
    { key: "AllTasks", value: "All Tasks" },
    { key: "NoOverdueTasks", value: "No overdue tasks" },
    { key: "YoureOnTrack", value: "Great! You're on track" },
    { key: "Refresh", value: "Refresh" },
    { key: "Month", value: "Month" },
    { key: "Week", value: "Week" },
    { key: "Day", value: "Day" },
    { key: "Today", value: "Today" },
    { key: "More", value: "More" },
    { key: "TaskDetail", value: "Task Detail" },
    { key: "ViewDetail", value: "View Detail" },
    { key: "StartDate", value: "Start Date" },
    { key: "DueDate", value: "Due Date" },
    { key: "AllPriorities", value: "All Priorities" },
    { key: "AllStatuses", value: "All Statuses" },

    // Settings
    { key: "SettingsDesc", value: "Manage your preferences and account settings" },
    { key: "Appearance", value: "Appearance" },
    { key: "AppearanceDesc", value: "Customize how the app looks and feels" },
    { key: "Theme", value: "Theme" },
    { key: "Notifications", value: "Notifications" },
    { key: "NotificationsDesc", value: "Choose what notifications you want to receive" },
    { key: "EmailNotifications", value: "Email notifications" },
    { key: "PushNotifications", value: "Push notifications" },
    { key: "TaskReminders", value: "Task reminders" },
    { key: "ProjectUpdates", value: "Project updates" },
    { key: "SystemAlerts", value: "System alerts" },
    { key: "MarketingEmails", value: "Marketing emails" },
    { key: "PrivacySecurity", value: "Privacy & Security" },
    { key: "PrivacySecurityDesc", value: "Control your privacy and security settings" },
    { key: "ProfileVisibility", value: "Profile visibility" },
    { key: "FriendsOnly", value: "Friends only" },
    { key: "ShowOnlineStatus", value: "Show online status" },
    { key: "AllowDirectMessages", value: "Allow direct messages" },
    { key: "DataSharing", value: "Data sharing with partners" },
    { key: "AnalyticsTracking", value: "Analytics tracking" },
    { key: "Preferences", value: "Preferences" },
    { key: "PreferencesDesc", value: "Customize your app experience" },
    { key: "AutoSaveDrafts", value: "Auto-save drafts" },
    { key: "ConfirmBeforeDelete", value: "Confirm before deleting" },
    { key: "ShowTips", value: "Show tips and hints" },
    { key: "CompactMode", value: "Compact mode" },
    { key: "SoundEffects", value: "Sound effects" },
    { key: "Animations", value: "Animations" },
    { key: "AccountInformation", value: "Account Information" },
    { key: "AccountInfoDesc", value: "Your account details and status" },
    { key: "AccountID", value: "Account ID" },
    { key: "Username", value: "Username" },
    { key: "Email", value: "Email" },
    { key: "Phone", value: "Phone" },
    { key: "Address", value: "Address" },
    { key: "Bio", value: "Bio" },
    { key: "MemberSince", value: "Member since" },
    { key: "LastLogin", value: "Last login" },
    { key: "Active", value: "Active" },
    { key: "SaveSettings", value: "Save Settings" },
    { key: "Saving", value: "Saving..." },
    { key: "Cancel", value: "Cancel" },
    { key: "Overview", value: "Overview" },
    { key: "EditProfile", value: "Edit Profile" },
    { key: "ChangePassword", value: "Change Password" },
    { key: "AccountSettings", value: "Account Settings" },
    { key: "ProfileOverview", value: "Profile Overview" },
    { key: "FullName", value: "Full Name" },
    { key: "SaveChanges", value: "Save Changes" },
    { key: "TellUsAboutYourself", value: "Tell us about yourself..." },
    { key: "CurrentPassword", value: "Current Password" },
    { key: "EnterCurrentPassword", value: "Enter current password" },
    { key: "NewPassword", value: "New Password" },
    { key: "EnterNewPassword", value: "Enter new password" },
    { key: "ConfirmNewPassword", value: "Confirm New Password" },
    { key: "AccountStatus", value: "Account Status" },
    { key: "TwoFactorAuth", value: "Two-Factor Authentication" },
    { key: "TwoFactorDesc", value: "Add an extra layer of security to your account" },
    { key: "Setup2FA", value: "Setup 2FA" },
    { key: "DangerZone", value: "Danger Zone" },
    { key: "IrreversibleAction", value: "Irreversible and destructive actions" },
    { key: "DeleteAccount", value: "Delete Account" },
    { key: "Edit", value: "Edit" },
    { key: "Changing", value: "Changing..." },

    // Project Detail
    { key: "List", value: "List" },
    { key: "Board", value: "Board" },
    { key: "Gantt", value: "Gantt" },
    { key: "Table", value: "Table" },
    { key: "Space", value: "Space" },
    { key: "Open", value: "Open" },
    { key: "Loading", value: "Loading..." },
    { key: "NoProjects", value: "No projects" },
    { key: "Agents", value: "Agents" },
    { key: "Automate", value: "Automate" },
    { key: "Ask", value: "Ask" },
    { key: "Share", value: "Share" },
    { key: "View", value: "View" },
    { key: "WelcomeToProject", value: "Welcome to" },
    { key: "ContentForView", value: "Content for {{view}} view goes here." },
    { key: "GroupNone", value: "Group: None" },
    { key: "Subtasks", value: "Subtasks" },
    { key: "Columns", value: "Columns" },
    { key: "SaveView", value: "Save view" },
    { key: "Filter", value: "Filter" },
    { key: "Closed", value: "Closed" },
    { key: "Assignee", value: "Assignee" },
    { key: "Search", value: "Search" },
    { key: "Customize", value: "Customize" },
    { key: "AddTask", value: "Add Task" },
    { key: "Name", value: "Name" },
    { key: "DueDate", value: "Due date" },
    { key: "Priority", value: "Priority" },
    { key: "Status", value: "Status" },
    { key: "Comments", value: "Comments" },
    { key: "AddTaskPlaceholder", value: "Add Task" },
    { key: "ProjectNotFound", value: "Project not found" },
    { key: "Projects", value: "Projects" },

    // Space Detail
    { key: "SpaceNotFound", value: "Space not found" },
    { key: "AddChannel", value: "Add Channel" },
    { key: "Filters", value: "Filters" },
    { key: "Refreshed", value: "Refreshed" },
    { key: "minsAgo", value: "mins ago" },
    { key: "AutoRefreshOn", value: "Auto refresh: On" },
    { key: "AddCard", value: "Add card" },
    { key: "InSpace", value: "in" },
    { key: "NoRecentProjects", value: "No recent projects" },
    { key: "NoDocsHere", value: "There are no Docs in this location yet." },
    { key: "AddDoc", value: "Add a Doc" },
    { key: "TasksByStatus", value: "Tasks by Status" },
    { key: "CompletionRate", value: "Completion" },
    { key: "Workload", value: "Workload" },
    { key: "OverdueTasks", value: "Overdue Tasks" },
    { key: "DueThisWeekTitle", value: "Due This Week" },
    { key: "NoTasksYet", value: "No tasks yet" },
    { key: "NoOverdue", value: "No overdue tasks! 🎉" },
    { key: "NothingDue", value: "Nothing due this week" },
    { key: "NoAssignments", value: "No task assignments yet" },
    { key: "NoMembers", value: "No members yet" },
    { key: "ViewAll", value: "View all" },
    { key: "Add", value: "Add" },
    { key: "New", value: "New" },
    { key: "EnterEmailPlaceholder", value: "Email / username..." },
    { key: "ChannelName", value: "Channel name" },
    { key: "EnterChannelName", value: "Enter channel name..." },
    { key: "DocumentName", value: "Document name" },
    { key: "EnterDocName", value: "Enter document name..." },
    { key: "Untitled", value: "Untitled" },
    { key: "tasks", value: "tasks" },
    { key: "done", value: "done" },
    { key: "overdue", value: "overdue" },
    { key: "completed", value: "completed" },

    // Space Detail Settings
    { key: "Dashboard", value: "Home" },
    { key: "CustomizeDashboard", value: "Customize layout" },
    { key: "DoneEditing", value: "Done editing" },
    { key: "AddCard", value: "Add card" },
    { key: "ResetLayout", value: "Reset layout" },
    { key: "Export", value: "Export" },
    { key: "ExportExcel", value: "Export Excel (CSV)" },
    { key: "PrintPDF", value: "Print / PDF" },
    { key: "Customize", value: "Customize" },
    { key: "members", value: "members" },
    { key: "AllSpaces", value: "All Spaces" },
    { key: "AllSpacesDesc", value: "Manage your organization's work environments, track global progress, and oversee team assignments across all departments." },
    { key: "ActiveSpaces", value: "Active Spaces" },
    { key: "CriticalOverdue", value: "Critical Overdue" },
    { key: "CreateNewSpace", value: "Create New Space" },
    { key: "CreateNewSpaceDesc", value: "Organize a new department" },
    { key: "Total", value: "Total" },
    { key: "Done", value: "Done" },
    { key: "NoDescription", value: "No description" },
    { key: "GoodMorning", value: "Good morning" },
    { key: "GoodAfternoon", value: "Good afternoon" },
    { key: "GoodEvening", value: "Good evening" },
    { key: "TodaySummary", value: "You have {tasks} tasks, {overdue} overdue, {dueWeek} due this week" },
    { key: "TasksOverdue", value: "tasks are overdue" },
    { key: "OverdueBannerDesc", value: "Review and update these tasks to keep your projects on track" },
    { key: "MyTasksToday", value: "My Tasks Today" },
    { key: "SearchSpaces", value: "Search spaces" },
    { key: "SortByName", value: "Sort by name" },
    { key: "SortByTasks", value: "Sort by tasks" },
    { key: "SortByOverdue", value: "Sort by overdue" },
    { key: "SortByProgress", value: "Sort by progress" },
    { key: "spaces", value: "spaces" },
    { key: "NoResultsFound", value: "No results found" },
    { key: "OpenSpace", value: "Open space" },
    { key: "Progress", value: "Progress" },
    { key: "RecentActivity", value: "Recent Activity" },
    { key: "NoRecentActivity", value: "No recent activity" },
    { key: "SearchProjects", value: "Search projects" },
    { key: "NewProject", value: "New Project" },
    { key: "TotalTasks", value: "Total Tasks" },
    { key: "CompletionRate", value: "Completion" },
    { key: "InProgress", value: "In Progress" },
    { key: "Overdue", value: "Overdue" },
    { key: "NoProjectsYet", value: "No projects yet" },
    { key: "NoProjectsYetDesc", value: "Create your first project to start organizing tasks" },
    { key: "CreateNewProjectDesc", value: "Organize tasks in a new project" },

    // Sidebar
    { key: "Rename", value: "Rename" },
    { key: "CopyLink", value: "Copy link" },
    { key: "CreateNew", value: "Create new" },
    { key: "Doc", value: "Doc" },
    { key: "Folder", value: "Folder" },
    { key: "ColorAndIcon", value: "Color & Icon" },
    { key: "Icon", value: "Icon" },
    { key: "SearchIcons", value: "Search icons..." },
    { key: "HideProject", value: "Hide Project" },
    { key: "HideSpace", value: "Hide Space" },
    { key: "HideProjectDesc", value: "You'll retain access to this Project, but it won't show in your sidebar" },
    { key: "HideSpaceDesc", value: "You'll retain access to this Space, but it won't show in your sidebar" },
    { key: "CreateSpace", value: "Create Space" },
    { key: "HiddenViews", value: "Hidden views" },
    { key: "AllViews", value: "All views" },
    { key: "HideView", value: "Hide this view" },
    { key: "Inactive", value: "Inactive" },
    { key: "ComingSoon", value: "Coming Soon" },
    { key: "AllStatuses", value: "All Statuses" },
    { key: "AllPriorities", value: "All Priorities" },
    { key: "Clear", value: "Clear" },
    { key: "Refresh", value: "Refresh" },
    { key: "SearchTasks", value: "Search tasks..." },
    { key: "Overdue", value: "Overdue" },
    { key: "ThisWeek", value: "Week" },
    { key: "ThisMonth", value: "Month" },
    { key: "NoDate", value: "No date" },
    { key: "All", value: "All" },
    { key: "SearchMembers", value: "Search members..." },
    { key: "Role", value: "Role" },
    { key: "Joined", value: "Joined" },
    { key: "Name", value: "Name" },

    // Create Task Modal
    { key: "PriorityUrgent", value: "Urgent" },
    { key: "PriorityHigh", value: "High" },
    { key: "PriorityNormal", value: "Normal" },
    { key: "PriorityLow", value: "Low" },
    { key: "SelectPriority", value: "Select Priority" },
    { key: "SetPriority", value: "Set Priority" },
    { key: "SetDueDate", value: "Set Due Date" },
    { key: "Today", value: "Today" },
    { key: "Tomorrow", value: "Tomorrow" },
    { key: "NextWeek", value: "Next Week" },
    { key: "NoDate", value: "No Date" },
    { key: "CustomDate", value: "Custom Date" },
    { key: "SelectAssignee", value: "Select Assignee" },
    { key: "ProTip", value: "Pro tip:" },
    { key: "QuickCreate", value: "to quick create" },
    { key: "ClickToUpload", value: "Click to upload or drag and drop" },
    { key: "ClickToUploadShort", value: "Click to upload" },
    { key: "ClickToUploadShort", value: "Click to upload" },
    { key: "FileTypes", value: "SVG, PNG, JPG or GIF (max. 10MB)" },
    { key: "TaskTitlePlaceholder", value: "What needs to be done?" },
    { key: "TaskDescriptionPlaceholder", value: "Add a detailed description... (Type '/' for commands)" },
    { key: "StartDate", value: "Start date" },
    { key: "Later", value: "Later" },
    { key: "ThisWeekend", value: "This weekend" },
    { key: "NextWeekend", value: "Next weekend" },
    { key: "TwoWeeks", value: "2 weeks" },
    { key: "FourWeeks", value: "4 weeks" },
    { key: "SetRecurring", value: "Set Recurring" },
    { key: "SelectDate", value: "Select date" },
    { key: "SelectStatus", value: "Select Status" },
    { key: "TaskCreatedSuccessfully", value: "Task created successfully!" },
    { key: "TaskCreationFailed", value: "Failed to create task. Please try again." },
    { key: "SpaceCreatedSuccessfully", value: "Space created successfully!" },
    { key: "SpaceCreationFailed", value: "Failed to create space. Please try again." },
    { key: "Done", value: "Done" },
    { key: "Review", value: "Review" },
    { key: "StatusCancel", value: "Cancel" },

    // Document
    { key: "Docs", value: "Docs" },
    { key: "Untitled Document", value: "Untitled Document" },
    { key: "New Document", value: "New Document" },
    { key: "Document name", value: "Document name" },
    { key: "Delete", value: "Delete" },
    { key: "Delete document", value: "Delete document" },
    { key: "Delete document confirm", value: "Are you sure you want to delete this document? This action cannot be undone." },
    { key: "Copy link", value: "Copy link" },
    { key: "Save", value: "Save" },
    { key: "Saved", value: "Saved" },
    { key: "Last saved", value: "Last saved" },
    { key: "Start typing...", value: "Start typing..." },
    { key: "Enter URL", value: "Enter URL" },
    { key: "Create", value: "Create" },
    { key: "Confirm delete document", value: "Are you sure you want to delete this document?" },
    { key: "New document", value: "New Document" },
    { key: "New Folder", value: "New Folder" },
    { key: "Folder name", value: "Folder name" },
    { key: "Enter folder name", value: "Enter folder name..." },
    { key: "Project", value: "Project" },
    { key: "Rename Folder", value: "Rename Folder" },
    { key: "Delete folder", value: "Delete Folder" },
    { key: "Delete folder confirm", value: "Are you sure you want to delete this folder? This action cannot be undone." },
    { key: "Folders", value: "Folders" },
    { key: "Save", value: "Save" },
    { key: "Created by", value: "Created by" },
    { key: "Subfolders", value: "Subfolders" },
    { key: "Empty folder", value: "Empty folder" },
    { key: "Empty folder desc", value: "Add projects, documents, or subfolders to start organizing your work." },
    { key: "New Project", value: "New Project" },
    { key: "New Subfolder", value: "New Subfolder" },
    { key: "Add item", value: "Add item" },
    { key: "Loading", value: "Loading..." },
    { key: "Total items", value: "Total items" },
    { key: "Open", value: "Open" },
    { key: "No results", value: "No results found" },
    { key: "Document title", value: "Document title" },
    { key: "Enter document title", value: "Enter title..." },
    { key: "Delete document", value: "Delete Document" },
    { key: "Delete document confirm", value: "Are you sure you want to delete this document?" },

    // Task Detail Modal
    { key: "TaskTitle", value: "Task title" },
    { key: "Description", value: "Description" },
    { key: "AddDescription", value: "Add a description..." },
    { key: "Activity", value: "Activity" },
    { key: "Attachments", value: "Attachments" },
    { key: "EditTask", value: "Edit Task" },
    { key: "DeleteTask", value: "Delete Task" },
    { key: "ConfirmDeleteTask", value: "Delete this task?" },
    { key: "ConfirmDeleteTaskMessage", value: "This action cannot be undone." },
    { key: "NoDueDate", value: "No due date" },
    { key: "NoStartDate", value: "No start date" },
    { key: "ClearDate", value: "Clear date" },
    { key: "Unassigned", value: "Unassigned" },
    { key: "DaysOverdue", value: "days overdue" },
    { key: "DueTomorrow", value: "Due tomorrow" },
    { key: "DaysLeft", value: "days left" },
    { key: "CreatedBy", value: "Created by" },
    { key: "CreatedAt", value: "Created at" },
    { key: "TaskDeleted", value: "Task deleted" },
    { key: "TaskDeleteFailed", value: "Failed to delete task" },
    { key: "TaskUpdateFailed", value: "Failed to update task" },
    { key: "TaskName", value: "Task Name" },
    { key: "WriteComment", value: "Write a comment..." },
    { key: "Comment", value: "Comment" },
    { key: "NoActivity", value: "No comments or activity yet" },
    { key: "Action_create_task", value: "created this task" },
    { key: "Action_update_task", value: "updated this task" },
    { key: "Action_delete_task", value: "deleted this task" },
    { key: "Action_update_status", value: "updated status" },
    { key: "Action_update_priority", value: "updated priority" },
    { key: "Action_add_assignee", value: "added assignee" },
    { key: "Action_remove_assignee", value: "removed assignee" },
    { key: "Action_update_priority_details", value: "changed priority from {{from}} to {{to}}" },
    { key: "Action_update_status_details", value: "changed status from {{from}} to {{to}}" },
    { key: "Action_set_date_details", value: "set {{field}} to {{date}}" },
    { key: "Action_remove_date_details", value: "removed {{field}}" },
    { key: "StartDate", value: "Start Date" },
    { key: "DueDate", value: "Due Date" },
    { key: "History", value: "History" }
];
