module.exports = [
    // General / Navigation
    { key: "Search", value: "Tìm kiếm" },
    { key: "Menu", value: "Menu" },
    { key: "MyTasks", value: "Công việc của tôi" },
    { key: "AssignedToMe", value: "Được giao cho tôi" },
    { key: "TodayAndOverdue", value: "Hôm nay & Quá hạn" },
    { key: "Spaces", value: "Không gian" },
    { key: "NewSpace", value: "Tạo mới không gian" },
    { key: "Channels", value: "Kênh" },
    { key: "Channel", value: "Kênh" },
    { key: "NewChannel", value: "Kênh mới" },
    { key: "TypeMessage", value: "Nhắn tin..." },
    { key: "NoMessages", value: "Chưa có tin nhắn" },
    { key: "StartConversation", value: "Bắt đầu cuộc trò chuyện!" },
    { key: "Members", value: "thành viên" },
    { key: "LoadMore", value: "Tải thêm" },
    { key: "Loading", value: "Đang tải..." },
    { key: "WelcomeBack", value: "Chào mừng trở lại" },
    { key: "Themes", value: "Chủ đề" },
    { key: "ChooseYourTheme", value: "Chọn giao diện" },
    { key: "ThemeDesc", value: "Tùy chỉnh giao diện ứng dụng của bạn" },
    { key: "LightMode", value: "Chế độ Sáng" },
    { key: "LightModeDesc", value: "Phù hợp cho môi trường sáng và làm việc chi tiết" },
    { key: "DarkMode", value: "Chế độ Tối" },
    { key: "DarkModeDesc", value: "Dễ chịu cho mắt, phù hợp điều kiện thiếu sáng" },
    { key: "SaveTheme", value: "Lưu giao diện" },
    { key: "NoChanges", value: "Không có thay đổi" },
    { key: "LightModePreview", value: "Xem trước Sáng" },
    { key: "DarkModePreview", value: "Xem trước Tối" },
    { key: "Dashboard", value: "Bảng điều khiển" },
    { key: "Calendar", value: "Lịch" },
    { key: "Messages", value: "Tin nhắn" },

    // Dashboard
    { key: "ProjectsIntro", value: "Đây là tình hình các dự án của bạn hôm nay" },
    { key: "TotalProjects", value: "Tổng dự án" },
    { key: "PendingTasks", value: "Công việc chờ" },
    { key: "Completed", value: "Đã hoàn thành" },
    { key: "NoActiveProjects", value: "Không có dự án hoạt động" },
    { key: "GetStartedProject", value: "Bắt đầu bằng cách tạo dự án mới hoặc mời thành viên vào nhóm." },
    { key: "CreateNewProject", value: "Tạo dự án mới" },
    { key: "LoadingDashboard", value: "Đang tải bảng điều khiển…" },
    { key: "Refresh", value: "Làm mới" },
    { key: "TotalTasks", value: "Tổng công việc" },
    { key: "InProgress", value: "Đang thực hiện" },
    { key: "Overdue", value: "Quá hạn" },
    { key: "TaskDistribution", value: "Phân bổ công việc" },
    { key: "NoData", value: "Không có dữ liệu" },
    { key: "NoOverdueTasks", value: "Không có công việc quá hạn!" },
    { key: "YoureOnTrack", value: "Bạn đang đúng tiến độ" },
    { key: "MySpaces", value: "Không gian của tôi" },
    { key: "NoSpacesYet", value: "Chưa có không gian nào" },
    { key: "DueThisWeek", value: "Hết hạn tuần này" },
    { key: "ByPriority", value: "Theo ưu tiên" },
    { key: "PriorityTasks", value: "Công việc ưu tiên" },
    { key: "Items", value: "Mục" },
    { key: "Task", value: "Công việc" },
    { key: "Tasks", value: "Công việc" },
    { key: "Context", value: "Ngữ cảnh" },
    { key: "Due", value: "Hạn" },
    { key: "NoPriorityTasks", value: "Không có công việc ưu tiên" },
    { key: "CreateTasksHint", value: "Tạo công việc trong dự án để xem tại đây" },
    { key: "RecentActivity", value: "Hoạt động gần đây" },
    { key: "On", value: "Trên" },
    { key: "NoRecentActivity", value: "Không có hoạt động gần đây" },
    { key: "QuickActions", value: "Thao tác nhanh" },
    { key: "ViewAllTasks", value: "Xem tất cả công việc" },
    { key: "BrowseProjects", value: "Duyệt dự án" },
    { key: "MyProfile", value: "Hồ sơ của tôi" },
    { key: "JustNow", value: "Vừa xong" },
    { key: "MinAgo", value: " phút trước" },
    { key: "HourAgo", value: " giờ trước" },
    { key: "DayAgo", value: " ngày trước" },
    { key: "High", value: "Cao" },
    { key: "Medium", value: "Trung bình" },
    { key: "Low", value: "Thấp" },
    { key: "Urgent", value: "Khẩn cấp" },
    { key: "None", value: "Không" },
    { key: "NoAssignedTasks", value: "Chưa có công việc nào được giao" },
    { key: "NoAssignedTasksHint", value: "Các công việc được giao cho bạn sẽ hiển thị tại đây" },
    { key: "DueToday", value: "Hôm nay" },
    { key: "OverdueDays", value: "Quá hạn {{days}} ngày" },
    { key: "NoTasksToday", value: "Không có công việc nào hôm nay" },
    { key: "NoTasksTodayHint", value: "Tuyệt vời! Bạn đã hoàn thành mọi thứ" },
    { key: "ToDo", value: "Cần làm" },
    { key: "InProgress", value: "Đang thực hiện" },
    { key: "Pending", value: "Đang chờ" },
    { key: "TotalTasks", value: "Tổng công việc" },
    { key: "ByPriority", value: "Theo mức ưu tiên" },
    { key: "CompletionOverview", value: "Tiến độ hoàn thành" },
    { key: "AllTasks", value: "Tất cả công việc" },
    { key: "NoOverdueTasks", value: "Không có công việc quá hạn" },
    { key: "YoureOnTrack", value: "Tuyệt vời! Bạn đang đúng tiến độ" },
    { key: "Refresh", value: "Làm mới" },
    { key: "Month", value: "Tháng" },
    { key: "Week", value: "Tuần" },
    { key: "Day", value: "Ngày" },
    { key: "Today", value: "Hôm nay" },
    { key: "More", value: "Thêm" },
    { key: "TaskDetail", value: "Chi tiết công việc" },
    { key: "ViewDetail", value: "Xem chi tiết" },
    { key: "StartDate", value: "Ngày bắt đầu" },
    { key: "DueDate", value: "Hạn chót" },
    { key: "AllPriorities", value: "Tất cả mức ưu tiên" },
    { key: "AllStatuses", value: "Tất cả trạng thái" },

    // Settings
    { key: "SettingsDesc", value: "Quản lý tùy chọn và cài đặt tài khoản" },
    { key: "Appearance", value: "Giao diện" },
    { key: "AppearanceDesc", value: "Tùy chỉnh giao diện ứng dụng" },
    { key: "Theme", value: "Chủ đề" },
    { key: "Notifications", value: "Thông báo" },
    { key: "NotificationsDesc", value: "Chọn loại thông báo bạn muốn nhận" },
    { key: "EmailNotifications", value: "Thông báo qua Email" },
    { key: "PushNotifications", value: "Thông báo đẩy" },
    { key: "TaskReminders", value: "Nhắc nhở công việc" },
    { key: "ProjectUpdates", value: "Cập nhật dự án" },
    { key: "SystemAlerts", value: "Cảnh báo hệ thống" },
    { key: "MarketingEmails", value: "Email quảng cáo" },
    { key: "PrivacySecurity", value: "Riêng tư & Bảo mật" },
    { key: "PrivacySecurityDesc", value: "Kiểm soát cài đặt riêng tư và bảo mật" },
    { key: "ProfileVisibility", value: "Hiển thị hồ sơ" },
    { key: "FriendsOnly", value: "Chỉ bạn bè" },
    { key: "ShowOnlineStatus", value: "Hiển thị trạng thái online" },
    { key: "AllowDirectMessages", value: "Cho phép tin nhắn trực tiếp" },
    { key: "DataSharing", value: "Chia sẻ dữ liệu với đối tác" },
    { key: "AnalyticsTracking", value: "Theo dõi phân tích" },
    { key: "Preferences", value: "Tùy chọn" },
    { key: "PreferencesDesc", value: "Tùy chỉnh trải nghiệm ứng dụng" },
    { key: "AutoSaveDrafts", value: "Tự động lưu nháp" },
    { key: "ConfirmBeforeDelete", value: "Xác nhận trước khi xóa" },
    { key: "ShowTips", value: "Hiển thị mẹo và gợi ý" },
    { key: "CompactMode", value: "Chế độ thu gọn" },
    { key: "SoundEffects", value: "Hiệu ứng âm thanh" },
    { key: "Animations", value: "Hiệu ứng chuyển động" },
    { key: "AccountInformation", value: "Thông tin tài khoản" },
    { key: "AccountInfoDesc", value: "Chi tiết và trạng thái tài khoản của bạn" },
    { key: "AccountID", value: "ID Tài khoản" },
    { key: "Username", value: "Tên đăng nhập" },
    { key: "Email", value: "Email" },
    { key: "Phone", value: "Số điện thoại" },
    { key: "Address", value: "Địa chỉ" },
    { key: "Bio", value: "Giới thiệu" },
    { key: "MemberSince", value: "Thành viên từ" },
    { key: "LastLogin", value: "Đăng nhập lần cuối" },
    { key: "Active", value: "Hoạt động" },
    { key: "SaveSettings", value: "Lưu cài đặt" },
    { key: "Saving", value: "Đang lưu..." },
    { key: "Cancel", value: "Hủy" },
    { key: "Overview", value: "Tổng quan" },
    { key: "EditProfile", value: "Chỉnh sửa hồ sơ" },
    { key: "ChangePassword", value: "Đổi mật khẩu" },
    { key: "AccountSettings", value: "Cài đặt tài khoản" },
    { key: "ProfileOverview", value: "Tổng quan hồ sơ" },
    { key: "FullName", value: "Họ và tên" },
    { key: "SaveChanges", value: "Lưu thay đổi" },
    { key: "TellUsAboutYourself", value: "Hãy giới thiệu về bản thân bạn..." },
    { key: "CurrentPassword", value: "Mật khẩu hiện tại" },
    { key: "EnterCurrentPassword", value: "Nhập mật khẩu hiện tại" },
    { key: "NewPassword", value: "Mật khẩu mới" },
    { key: "EnterNewPassword", value: "Nhập mật khẩu mới" },
    { key: "ConfirmNewPassword", value: "Xác nhận mật khẩu mới" },
    { key: "AccountStatus", value: "Trạng thái tài khoản" },
    { key: "TwoFactorAuth", value: "Xác thực hai yếu tố (2FA)" },
    { key: "TwoFactorDesc", value: "Thêm một lớp bảo mật cho tài khoản của bạn" },
    { key: "Setup2FA", value: "Thiết lập 2FA" },
    { key: "DangerZone", value: "Khu vực nguy hiểm" },
    { key: "IrreversibleAction", value: "Hành động không thể hoàn tác" },
    { key: "DeleteAccount", value: "Xóa tài khoản" },
    { key: "Edit", value: "Chỉnh sửa" },
    { key: "Changing", value: "Đang đổi..." },

    // Project Detail
    { key: "List", value: "Danh sách" },
    { key: "Board", value: "Bảng" },
    { key: "Gantt", value: "Gantt" },
    { key: "Table", value: "Bảng tính" },
    { key: "Space", value: "Không gian" },
    { key: "Open", value: "Mở" },
    { key: "Loading", value: "Đang tải..." },
    { key: "NoProjects", value: "Không có dự án" },
    { key: "Agents", value: "Agents" },
    { key: "Automate", value: "Tự động hóa" },
    { key: "Ask", value: "Hỏi" },
    { key: "Share", value: "Chia sẻ" },
    { key: "View", value: "Xem" },
    { key: "WelcomeToProject", value: "Chào mừng đến với" },
    { key: "ContentForView", value: "Nội dung cho chế độ xem {{view}} hiển thị ở đây." },
    { key: "GroupNone", value: "Nhóm: Không" },
    { key: "Subtasks", value: "Công việc con" },
    { key: "Columns", value: "Cột" },
    { key: "SaveView", value: "Lưu chế độ xem" },
    { key: "Filter", value: "Bộ lọc" },
    { key: "Closed", value: "Đã đóng" },
    { key: "Assignee", value: "Người thực hiện" },
    { key: "Search", value: "Tìm kiếm" },
    { key: "Customize", value: "Tùy chỉnh" },
    { key: "AddTask", value: "Thêm công việc" },
    { key: "Name", value: "Tên" },
    { key: "DueDate", value: "Ngày hết hạn" },
    { key: "Priority", value: "Độ ưu tiên" },
    { key: "Status", value: "Trạng thái" },
    { key: "Comments", value: "Bình luận" },
    { key: "AddTaskPlaceholder", value: "Thêm công việc" },
    { key: "ProjectNotFound", value: "Không tìm thấy dự án" },
    { key: "Projects", value: "Dự án" },

    // Space Detail
    { key: "SpaceNotFound", value: "Không tìm thấy không gian" },
    { key: "AddChannel", value: "Thêm kênh" },
    { key: "Filters", value: "Bộ lọc" },
    { key: "Refreshed", value: "Đã làm mới" },
    { key: "minsAgo", value: "phút trước" },
    { key: "AutoRefreshOn", value: "Tự động làm mới: Bật" },
    { key: "AddCard", value: "Thêm thẻ" },
    { key: "InSpace", value: "trong" },
    { key: "NoRecentProjects", value: "Không có dự án gần đây" },
    { key: "NoDocsHere", value: "Chưa có tài liệu nào ở đây." },
    { key: "AddDoc", value: "Thêm tài liệu" },
    { key: "TasksByStatus", value: "Công việc theo trạng thái" },
    { key: "CompletionRate", value: "Tiến độ" },
    { key: "Workload", value: "Khối lượng công việc" },
    { key: "OverdueTasks", value: "Công việc quá hạn" },
    { key: "DueThisWeekTitle", value: "Hết hạn tuần này" },
    { key: "NoTasksYet", value: "Chưa có công việc" },
    { key: "NoOverdue", value: "Không có công việc quá hạn! 🎉" },
    { key: "NothingDue", value: "Không có gì hết hạn tuần này" },
    { key: "NoAssignments", value: "Chưa có phân công công việc" },
    { key: "NoMembers", value: "Chưa có thành viên" },
    { key: "ViewAll", value: "Xem tất cả" },
    { key: "Add", value: "Thêm" },
    { key: "New", value: "Mới" },
    { key: "EnterEmailPlaceholder", value: "Email / tên đăng nhập..." },
    { key: "ChannelName", value: "Tên kênh" },
    { key: "EnterChannelName", value: "Nhập tên kênh..." },
    { key: "DocumentName", value: "Tên tài liệu" },
    { key: "EnterDocName", value: "Nhập tên tài liệu..." },
    { key: "Untitled", value: "Chưa đặt tên" },
    { key: "tasks", value: "công việc" },
    { key: "done", value: "xong" },
    { key: "overdue", value: "quá hạn" },
    { key: "completed", value: "hoàn thành" },

    // Space Detail Settings
    { key: "Dashboard", value: "Trang Home" },
    { key: "CustomizeDashboard", value: "Tùy chỉnh giao diện" },
    { key: "DoneEditing", value: "Hoàn tất chỉnh sửa" },
    { key: "AddCard", value: "Thêm thẻ" },
    { key: "ResetLayout", value: "Đặt lại bố cục" },
    { key: "Export", value: "Xuất dữ liệu" },
    { key: "ExportExcel", value: "Xuất Excel (CSV)" },
    { key: "PrintPDF", value: "In / Xuất PDF" },
    { key: "Customize", value: "Tùy chỉnh" },
    { key: "members", value: "thành viên" },
    { key: "AllSpaces", value: "Tất cả không gian" },
    { key: "AllSpacesDesc", value: "Quản lý các không gian làm việc, theo dõi tiến độ tổng thể và giám sát công việc của các bộ phận." },
    { key: "ActiveSpaces", value: "Không gian" },
    { key: "CriticalOverdue", value: "Quá hạn" },
    { key: "CreateNewSpace", value: "Tạo không gian mới" },
    { key: "CreateNewSpaceDesc", value: "Tổ chức một bộ phận mới" },
    { key: "Total", value: "Tổng" },
    { key: "Done", value: "Xong" },
    { key: "NoDescription", value: "Chưa có mô tả" },
    { key: "GoodMorning", value: "Chào buổi sáng" },
    { key: "GoodAfternoon", value: "Chào buổi chiều" },
    { key: "GoodEvening", value: "Chào buổi tối" },
    { key: "TodaySummary", value: "Bạn có {tasks} công việc, {overdue} quá hạn, {dueWeek} hết hạn tuần này" },
    { key: "TasksOverdue", value: "công việc đã quá hạn" },
    { key: "OverdueBannerDesc", value: "Xem lại và cập nhật để dự án đúng tiến độ" },
    { key: "MyTasksToday", value: "Công việc hôm nay" },
    { key: "SearchSpaces", value: "Tìm không gian" },
    { key: "SortByName", value: "Sắp xếp theo tên" },
    { key: "SortByTasks", value: "Theo số công việc" },
    { key: "SortByOverdue", value: "Theo quá hạn" },
    { key: "SortByProgress", value: "Theo tiến độ" },
    { key: "spaces", value: "không gian" },
    { key: "NoResultsFound", value: "Không tìm thấy kết quả" },
    { key: "OpenSpace", value: "Mở không gian" },
    { key: "Progress", value: "Tiến độ" },
    { key: "RecentActivity", value: "Hoạt động gần đây" },
    { key: "NoRecentActivity", value: "Chưa có hoạt động" },
    { key: "SearchProjects", value: "Tìm dự án" },
    { key: "NewProject", value: "Dự án mới" },
    { key: "TotalTasks", value: "Tổng công việc" },
    { key: "CompletionRate", value: "Hoàn thành" },
    { key: "InProgress", value: "Đang làm" },
    { key: "Overdue", value: "Quá hạn" },
    { key: "NoProjectsYet", value: "Chưa có dự án" },
    { key: "NoProjectsYetDesc", value: "Tạo dự án đầu tiên để bắt đầu quản lý công việc" },
    { key: "CreateNewProjectDesc", value: "Tổ chức công việc trong dự án mới" },

    // Sidebar
    { key: "Rename", value: "Đổi tên" },
    { key: "CopyLink", value: "Sao chép liên kết" },
    { key: "CreateNew", value: "Tạo mới" },
    { key: "Doc", value: "Tài liệu" },
    { key: "Folder", value: "Thư mục" },
    { key: "ColorAndIcon", value: "Màu sắc & Biểu tượng" },
    { key: "Icon", value: "Biểu tượng" },
    { key: "SearchIcons", value: "Tìm kiếm biểu tượng..." },
    { key: "HideProject", value: "Ẩn dự án" },
    { key: "HideSpace", value: "Ẩn không gian" },
    { key: "HideProjectDesc", value: "Bạn vẫn có quyền truy cập dự án này, nhưng nó sẽ không hiện trên thanh bên" },
    { key: "HideSpaceDesc", value: "Bạn vẫn có quyền truy cập không gian này, nhưng nó sẽ không hiện trên thanh bên" },
    { key: "CreateSpace", value: "Tạo không gian" },
    { key: "HiddenViews", value: "Các view đã ẩn" },
    { key: "AllViews", value: "Tất cả view" },
    { key: "HideView", value: "Ẩn view này" },
    { key: "Inactive", value: "Không hoạt động" },
    { key: "ComingSoon", value: "Sắp ra mắt" },
    { key: "AllStatuses", value: "Tất cả trạng thái" },
    { key: "AllPriorities", value: "Tất cả ưu tiên" },
    { key: "Clear", value: "Xóa bộ lọc" },
    { key: "Refresh", value: "Làm mới" },
    { key: "SearchTasks", value: "Tìm kiếm task..." },
    { key: "Overdue", value: "Quá hạn" },
    { key: "ThisWeek", value: "Tuần" },
    { key: "ThisMonth", value: "Tháng" },
    { key: "NoDate", value: "Không có ngày" },
    { key: "All", value: "Tất cả" },
    { key: "SearchMembers", value: "Tìm thành viên..." },
    { key: "Role", value: "Vai trò" },
    { key: "Joined", value: "Ngày tham gia" },
    { key: "Name", value: "Tên" },

    // Create Task Modal
    { key: "PriorityUrgent", value: "Khẩn cấp" },
    { key: "PriorityHigh", value: "Cao" },
    { key: "PriorityNormal", value: "Bình thường" },
    { key: "PriorityLow", value: "Thấp" },
    { key: "SelectPriority", value: "Chọn độ ưu tiên" },
    { key: "SetPriority", value: "Đặt độ ưu tiên" },
    { key: "SetDueDate", value: "Đặt ngày hết hạn" },
    { key: "Today", value: "Hôm nay" },
    { key: "Tomorrow", value: "Ngày mai" },
    { key: "NextWeek", value: "Tuần tới" },
    { key: "NoDate", value: "Không có ngày" },
    { key: "CustomDate", value: "Ngày tùy chọn" },
    { key: "SelectAssignee", value: "Chọn người thực hiện" },
    { key: "ProTip", value: "Mẹo:" },
    { key: "QuickCreate", value: "để tạo nhanh" },
    { key: "ClickToUpload", value: "Nhấn để tải lên hoặc kéo thả" },
    { key: "ClickToUploadShort", value: "Nhấn để tải lên" },
    { key: "ClickToUploadShort", value: "Nhấn để tải lên" },
    { key: "FileTypes", value: "SVG, PNG, JPG hoặc GIF (tối đa 10MB)" },
    { key: "TaskTitlePlaceholder", value: "Cần làm những gì?" },
    { key: "TaskDescriptionPlaceholder", value: "Thêm mô tả chi tiết... (Gõ '/' cho các lệnh)" },
    { key: "StartDate", value: "Ngày bắt đầu" },
    { key: "Later", value: "Sau đó" },
    { key: "ThisWeekend", value: "Cuối tuần này" },
    { key: "NextWeekend", value: "Cuối tuần sau" },
    { key: "TwoWeeks", value: "2 tuần" },
    { key: "FourWeeks", value: "4 tuần" },
    { key: "SetRecurring", value: "Lặp lại" },
    { key: "SelectDate", value: "Chọn ngày" },
    { key: "SelectStatus", value: "Chọn trạng thái" },
    { key: "TaskCreatedSuccessfully", value: "Tạo công việc thành công!" },
    { key: "TaskCreationFailed", value: "Tạo công việc thất bại. Vui lòng thử lại." },
    { key: "SpaceCreatedSuccessfully", value: "Tạo không gian thành công!" },
    { key: "SpaceCreationFailed", value: "Tạo không gian thất bại. Vui lòng thử lại." },
    { key: "Done", value: "Xong" },
    { key: "Review", value: "Xem lại" },
    { key: "StatusCancel", value: "Hủy bỏ" },

    // Document
    { key: "Docs", value: "Tài liệu" },
    { key: "Untitled Document", value: "Tài liệu chưa có tiêu đề" },
    { key: "New Document", value: "Tài liệu mới" },
    { key: "Document name", value: "Tên tài liệu" },
    { key: "Delete", value: "Xoá" },
    { key: "Delete document", value: "Xoá tài liệu" },
    { key: "Delete document confirm", value: "Bạn có chắc muốn xoá tài liệu này? Hành động này không thể hoàn tác." },
    { key: "Copy link", value: "Sao chép liên kết" },
    { key: "Save", value: "Lưu" },
    { key: "Saved", value: "Đã lưu" },
    { key: "Last saved", value: "Lưu lần cuối" },
    { key: "Start typing...", value: "Bắt đầu nhập nội dung..." },
    { key: "Enter URL", value: "Nhập URL" },
    { key: "Create", value: "Tạo" },
    { key: "Confirm delete document", value: "Bạn có chắc muốn xoá tài liệu này?" },
    { key: "New document", value: "Tài liệu mới" },
    { key: "New Folder", value: "Thư mục mới" },
    { key: "Folder name", value: "Tên thư mục" },
    { key: "Enter folder name", value: "Nhập tên thư mục..." },
    { key: "Project", value: "Dự án" },
    { key: "Rename Folder", value: "Đổi tên thư mục" },
    { key: "Delete folder", value: "Xoá thư mục" },
    { key: "Delete folder confirm", value: "Bạn có chắc muốn xoá thư mục này? Hành động này không thể hoàn tác." },
    { key: "Folders", value: "Thư mục" },
    { key: "Save", value: "Lưu" },
    { key: "Created by", value: "Tạo bởi" },
    { key: "Subfolders", value: "Thư mục con" },
    { key: "Empty folder", value: "Thư mục trống" },
    { key: "Empty folder desc", value: "Thêm dự án, tài liệu hoặc thư mục con để bắt đầu tổ chức công việc." },
    { key: "New Project", value: "Tạo dự án" },
    { key: "New Subfolder", value: "Thư mục con" },
    { key: "Add item", value: "Thêm mục" },
    { key: "Loading", value: "Đang tải..." },
    { key: "Total items", value: "Tổng mục" },
    { key: "Open", value: "Mở" },
    { key: "No results", value: "Không tìm thấy kết quả" },
    { key: "Document title", value: "Tiêu đề tài liệu" },
    { key: "Enter document title", value: "Nhập tiêu đề..." },
    { key: "Delete document", value: "Xoá tài liệu" },
    { key: "Delete document confirm", value: "Bạn có chắc muốn xoá tài liệu này?" },

    // Task Detail Modal
    { key: "TaskTitle", value: "Tiêu đề công việc" },
    { key: "Description", value: "Ghi chú" },
    { key: "AddDescription", value: "Thêm mô tả..." },
    { key: "Activity", value: "Hoạt động" },
    { key: "Attachments", value: "Tệp đính kèm" },
    { key: "EditTask", value: "Chỉnh sửa công việc" },
    { key: "DeleteTask", value: "Xóa công việc" },
    { key: "ConfirmDeleteTask", value: "Xóa công việc này?" },
    { key: "ConfirmDeleteTaskMessage", value: "Hành động này không thể hoàn tác." },
    { key: "NoDueDate", value: "Chưa đặt hạn" },
    { key: "NoStartDate", value: "Chưa đặt ngày" },
    { key: "ClearDate", value: "Xóa ngày" },
    { key: "Unassigned", value: "Chưa phân công" },
    { key: "DaysOverdue", value: "ngày quá hạn" },
    { key: "DueTomorrow", value: "Hạn ngày mai" },
    { key: "DaysLeft", value: "ngày còn lại" },
    { key: "CreatedBy", value: "Được tạo bởi" },
    { key: "CreatedAt", value: "Ngày tạo" },
    { key: "TaskDeleted", value: "Đã xóa công việc" },
    { key: "TaskDeleteFailed", value: "Xóa công việc thất bại" },
    { key: "TaskUpdateFailed", value: "Cập nhật công việc thất bại" },
    { key: "TaskName", value: "Tên công việc" },
    { key: "WriteComment", value: "Viết bình luận..." },
    { key: "Comment", value: "Bình luận" },
    { key: "NoActivity", value: "Chưa có hoạt động hay bình luận nào" },
    { key: "Action_create_task", value: "đã tạo công việc" },
    { key: "Action_update_task", value: "đã cập nhật công việc" },
    { key: "Action_delete_task", value: "đã xóa công việc" },
    { key: "Action_update_status", value: "đã thay đổi trạng thái" },
    { key: "Action_update_priority", value: "đã thay đổi mức độ ưu tiên" },
    { key: "Action_add_assignee", value: "đã thêm người thực hiện" },
    { key: "Action_remove_assignee", value: "đã gỡ người thực hiện" },
    { key: "Action_update_priority_details", value: "đã đổi mức độ ưu tiên từ {{from}} sang {{to}}" },
    { key: "Action_update_status_details", value: "đã đổi trạng thái từ {{from}} sang {{to}}" },
    { key: "Action_set_date_details", value: "đã đặt {{field}} thành {{date}}" },
    { key: "Action_remove_date_details", value: "đã xóa {{field}}" },
    { key: "StartDate", value: "Ngày bắt đầu" },
    { key: "DueDate", value: "Ngày hết hạn" },
    { key: "History", value: "Lịch sử" }
];
