module.exports =[
    {key:"Profile",value:"Profile"},
    {key:"ChangePassword",value:"Change Password"},
    {key:"Signout",value:"Signout"},
    {key:"EditAvatar",value:"Edit Avata"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Profile Photo Will Changed Automatically"},
    {key:"UploadNewPhoto",value:"Upload New Photo"},
    {key:"Update",value:"Update"},
    {key:"PersonalInfomation",value:"Personal Infomation"},
    {key:"PersonalStatistics",value:"Personal Statistics"},
    {key:"RecentNotifyReceived",value:"Recent Notify Received"},
    {key:"ViewMore",value:"View More"},
    {key:"Collapse",value:"Collapse"},
    {key:"RecentInfomations",value:"Recent Infomations"},
    {key:"MySettings",value:"My Settings"},
    {key:"Tenants",value:"Tenants"},
    {key:"ProfileDescription",value:"Your personal information and account security settings."},
    {key:"Avatar",value:"Avatar"},
    {key:"FullName",value:"Full Name"},
    {key:"Password",value:"Password"},
    {key:"User",value:"User"},
    {key:"EmailAddress",value:"Email address"},
    {key:"EmailCannotBeChanged",value:"Email cannot be changed as it has been verified"},
    {key:"EnterNewPassword",value:"Enter New Password"},
    {key:"AppearanceDescription",value:"Choose light or dark mode, or switch your mode automatically based on your system settings."},
    {key:"Light",value:"Light"},
    {key:"Dark",value:"Dark"},
    {key:"SaveChanges",value:"Save Changes"},
    {key:"ProfileUpdatedSuccessfully",value:"Profile updated successfully"},
    {key:"FailedToUpdateProfile",value:"Failed to update profile. Please try again."},
    {key:"PasswordManagedByGoogle",value:"Password managed by Google"},
    {key:"PasswordManagedByGoogleDescription",value:"Your account is signed in with Google, so you cannot change your password here."},
    {key:"AllSettings",value:"All settings"},
    {key:"People",value:"People"},
    {key:"General",value:"General"},
    {key:"Spaces",value:"Spaces"},
    {key:"LogOut",value:"Log out"},
    {key:"ProfileSettings",value:"Profile Settings"},
    {key:"MyTenants",value:"My Tenants"},
    {key:"LoadingTenants",value:"Loading tenants..."},
    {key:"FreeForever",value:"Free Forever"},
    {key:"Person",value:"person"},
    {key:"Settings",value:"Settings"},
    {key:"Leave",value:"Leave"},
    {key:"ManagePeople",value:"Manage people"},
    {key:"SearchOrInviteByEmail",value:"Search or invite by email"},
    {key:"InvitePeople",value:"Invite people"},
    {key:"AllUsers",value:"All Users"},
    {key:"Owner",value:"Owner"},
    {key:"Admin",value:"Admin"},
    {key:"Member",value:"Member"},
    {key:"Name",value:"Name"},
    {key:"Email",value:"Email"},
    {key:"Role",value:"Role"},
    {key:"Status",value:"Status"},
    {key:"LastActive",value:"Last active"},
    {key:"InvitedBy",value:"Invited by"},
    {key:"InvitedOn",value:"Invited on"},
    {key:"NoMembersFound",value:"No members found"},
    {key:"Today",value:"Today"},
    {key:"Yesterday",value:"Yesterday"},
    {key:"DaysAgo",value:"{{count}} days ago"},
    {key:"ProjectInvitation",value:"Project Invitation"},
    {key:"InvitationSentSuccess",value:"Invitation sent successfully to Gmail!"},
    {key:"FailedToSendInvitation",value:"Failed to send invitation. Please try again."},
    {key:"OnlyGmailAllowed",value:"Only @gmail.com addresses are allowed for invitations."},
    {key:"EnterGmailInvite",value:"Enter recipient's Gmail address"},
    {key:"Pending",value:"Pending"},
    {key:"AcceptingInvitation",value:"Accepting invitation..."},
    {key:"InvitationAccepted",value:"Invitation accepted!"},
    {key:"AcceptFailed",value:"Failed to accept invitation"},
    {key:"ResendInvitation",value:"Resend invitation"},
    {key:"CancelInvite",value:"Cancel invite"},
    {key:"SetAsAdmin",value:"Set as admin"},
    {key:"SetAsMember",value:"Set as member"},
    {key:"Remove",value:"Remove"},
    {key:"GeneralSettings",value:"General Settings"},
    {key:"TenantInformation",value:"Tenant Information"},
    {key:"TenantInformationDescriptionOwner",value:"Manage your tenant's general settings and information. Only the owner can modify these settings."},
    {key:"TenantInformationDescriptionViewer",value:"View your tenant's general settings and information."},
    {key:"TenantAvatar",value:"Tenant Avatar"},
    {key:"OnlyOwnerCanChangeTenantAvatar",value:"Only the owner can change the tenant avatar"},
    {key:"TenantName",value:"Tenant Name"},
    {key:"OnlyOwnerCanChangeTenantName",value:"Only the owner can change the tenant name"},
    {key:"Members",value:"Members"},
    {key:"LoadingTenantInformation",value:"Loading tenant information..."},
    {key:"NewSpace",value:"New Space"},
    {key:"LoadingSpaces",value:"Loading spaces..."},
    {key:"NoSpacesFound",value:"No spaces found"},
    {key:"NoSpacesYet",value:"No spaces yet"},
    {key:"Space",value:"SPACE"},
    {key:"Visibility",value:"VISIBILITY"},
    {key:"SharedWith",value:"SHARED WITH"},
    {key:"GoToSpace",value:"Go to Space"},
    {key:"Private",value:"Private"},
    {key:"Public",value:"Public"},
    {key:"OnlyInvitedMembers",value:"Only invited members"},
    {key:"Everyone",value:"Everyone"},
    {key:"Share",value:"Share"},
    {key:"MakePrivate",value:"Make private"},
    {key:"ThisSectionComingSoon",value:"This section is coming soon."},
    {key:"RemoveMember",value:"Remove Member"},
    {key:"RemoveMemberConfirmMessage",value:"Are you sure you want to remove {{name}} from this workspace? This action cannot be undone."},
    {key:"ThisMember",value:"this member"},
    {key:"Cancel",value:"Cancel"},
    {key:"Saving",value:"Saving..."},
    {key:"InvitationResentSuccessfully",value:"Invitation resent successfully"},
    {key:"ResendFailed",value:"Resend failed"},
    {key:"CanceledInvite",value:"Canceled invite"},
    {key:"CancelFailed",value:"Cancel failed"},
    {key:"TenantIdMissing",value:"Tenant ID is missing"},
    {key:"MemberUsernameMissing",value:"Member username is missing"},
    {key:"ServiceMethodNotAvailable",value:"Service method not available. Please refresh the page."},
    {key:"MemberRoleUpdatedToAdmin",value:"Member role updated to admin"},
    {key:"MemberRoleUpdatedToMember",value:"Member role updated to member"},
    {key:"FailedToSetAsAdmin",value:"Failed to set as admin. Please try again."},
    {key:"FailedToSetAsMember",value:"Failed to set as member. Please try again."},
    {key:"AvatarUploadComingSoon",value:"Avatar upload coming soon"},
    {key:"TenantUpdatedSuccessfully",value:"Tenant updated successfully"},
    {key:"FailedToUpdateTenant",value:"Failed to update tenant"},
    {key:"MemberRemovedSuccessfully",value:"Member removed successfully"},
    {key:"FailedToRemoveMember",value:"Failed to remove member"},
    {key:"FailedToLoadSpaces",value:"Failed to load spaces"},
    {key:"FailedToLoadWorkspaces",value:"Failed to load workspaces"},
    {key:"FailedToLoadMembers",value:"Failed to load members"},
    {key:"AvatarUploadedSuccessfully",value:"Avatar uploaded successfully"},
    {key:"FailedToUploadAvatar",value:"Failed to upload avatar"},
    // Mobile App New Keys
    {key:"EditProfile",value:"Edit Profile"},
    {key:"NotificationSettings",value:"Notification Settings"},
    {key:"InviteUsers",value:"Invite Users"},
    {key:"HelpAndResources",value:"Help & Resources"},
    {key:"Online",value:"Online"},
    {key:"EmailCopied",value:"Email copied successfully"},
    {key:"Teams",value:"Teams"},
    {key:"MuteNotifications",value:"Mute Notifications"},
    {key:"NotificationsMuted",value:"Notifications muted"},
    {key:"NotificationsUnmuted",value:"Notifications unmuted"},
    {key:"NameCannotBeEmpty",value:"Name cannot be empty"},
    {key:"UpdateProfileSuccess",value:"Profile updated successfully"},
    {key:"UpdateProfileFailed",value:"Failed to update profile"},
    {key:"App",value:"App"},
    {key:"Account",value:"Account"},
    {key:"DefaultLaunchPage",value:"Default Page"},
    {key:"Sound",value:"Sound"},
    {key:"ResetPassword",value:"Reset Password"},
    {key:"DeleteAccount",value:"Delete Account"},
    {key:"LightMode",value:"Light Mode"},
    {key:"DarkMode",value:"Dark Mode"},
    {key:"SystemMode",value:"System Mode"},
    {key:"WelcomeBack",value:"Welcome back"},
    {key:"GoodMorning",value:"Good morning"},
    {key:"GoodAfternoon",value:"Good afternoon"},
    {key:"GoodEvening",value:"Good evening"},
    {key:"GoodNight",value:"Good night"},
    {key:"MyWorkspace",value:"My Workspace"},
    {key:"MarkAllRead",value:"Mark all as read"},
    {key:"CreateNew",value:"Create New"},
    {key:"CreateSpaceDesc",value:"Create a high-level workspace for your team or department."},
    {key:"CreateProjectDesc",value:"Organize related tasks into a common roadmap."},
    {key:"CreateTaskDesc",value:"Create a new assigned piece of work."},
    {key:"MySpaces",value:"My Spaces"},
    {key:"PendingTasks",value:"Pending Tasks"},
    {key:"NoPendingTasks",value:"No pending tasks"},
    {key:"TaskProgress",value:"Task Progress"},
    {key:"InProgress",value:"In Progress"},
    {key:"Tasks",value:"Tasks"},
    {key:"CouldNotLoadTasks",value:"Could not load tasks"},
    {key:"Retry",value:"Retry"},
    {key:"NoTasksFound",value:"No tasks found"},
    {key:"Search",value:"Search"},
    {key:"AnonymousUser",value:"Anonymous User"},
    {key:"Notifications",value:"Notifications"},
    {key:"WorkspaceOverview",value:"Workspace Overview"},
    {key:"Home",value:"Home"},
    {key:"Chat",value:"Chat"},
    {key:"Docs",value:"Docs"},
    {key:"Planner",value:"Planner"},
    {key:"Projects",value:"Projects"},
    {key:"ResetPasswordDescription",value:"For security reasons, please visit our website to securely reset your password."},
    {key:"GoToWebsite",value:"Go to Website"},
    {key:"BackToSignIn",value:"Back to Sign In"},
    {key:"DeleteAccountConfirmation",value:"Are you sure you want to permanently delete your account? This action cannot be undone and all your data will be lost."},
    {key:"Delete",value:"Delete"},
    {key:"NotificationSettings",value:"Notification Settings"},
    {key:"MasterControl",value:"Master Control"},
    {key:"MuteAll",value:"Mute All"},
    {key:"MuteAllDescription",value:"Silence all notifications instantly"},
    {key:"Sound",value:"Sound"},
    {key:"SoundDescription",value:"Play sound for incoming alerts"},
    {key:"ActivityAlerts",value:"Activity Alerts"},
    {key:"NotifyAssigned",value:"Task Assignments"},
    {key:"NotifyAssignedDesc",value:"Get notified when a new task is assigned to you"},
    {key:"NotifyComment",value:"Comments & Mentions"},
    {key:"NotifyCommentDesc",value:"Get notified when someone comments or mentions you"},
    {key:"NotifyDeadline",value:"Deadline Reminders"},
    {key:"NotifyDeadlineDesc",value:"Get notified about upcoming task deadlines"},
    {key:"Channels",value:"Channels"},
    {key:"EmailNotifications",value:"Email Notifications"},
    {key:"EmailNotificationsDesc",value:"Receive a daily summary of your activities"},
    {key:"SupportHub",value:"Support Hub"},
    {key:"HelpCenter",value:"Help Center"},
    {key:"HelpCenterDesc",value:"Articles and tutorials"},
    {key:"ContactSupport",value:"Contact Support"},
    {key:"ContactSupportDesc",value:"Get help from our team"},
    {key:"Community",value:"Community"},
    {key:"CommunityDesc",value:"Join our Discord server"},
    {key:"LegalPrivacy",value:"Legal & Privacy"},
    {key:"PrivacyPolicy",value:"Privacy Policy"},
    {key:"PrivacyPolicyDesc",value:"How we handle your data"},
    {key:"TermsOfService",value:"Terms of Service"},
    {key:"TermsOfServiceDesc",value:"Rules for using our service"},
    {key:"Licenses",value:"Open Source Licenses"},
    {key:"LicensesDesc",value:"Credits for third-party software"},
    {key:"Version",value:"Version"},
    {key:"Build",value:"Build"},
    {key:"TasksCompletedCount",value:"{completed} of {total} tasks completed"},
    {key:"OverviewLabel",value:"OVERVIEW"},
    {key:"TodaysTasks",value:"TODAY'S TASKS"},
    {key:"ActiveTasks",value:"Active tasks"},
    {key:"OverdueCaps",value:"OVERDUE"},
    {key:"CompletedCaps",value:"COMPLETED"},
    {key:"SeeAll",value:"SEE ALL"},
    {key:"QuickAlerts",value:"Quick Alerts"},
    {key:"RecentSpaces",value:"Recent Spaces"},
    {key:"LatestProjects",value:"Latest Projects"},
    {key:"ConnectionError",value:"Connection Error"},
    {key:"ProjectsCount",value:"{count} Projects"},
    {key:"AlertSarahUpdate",value:"Sarah updated \"Q4 Roadmap\""},
    {key:"AlertDeadlineDocs",value:"Deadline approach: \"API Docs\""},
    {key:"MinutesAgo",value:"{count} minutes ago"},
    {key:"HoursAgo",value:"{count} hour ago"},
    {key:"NewVenture",value:"New Venture"},
    {key:"NoRecentActivity",value:"No recent activity to show"},
    {key:"NoProjectsFound",value:"No projects found"},
    {key:"TasksCount",value:"{count} Tasks"},
    {key:"PinnedSpaces",value:"Pinned Spaces"},
    {key:"NoPinnedSpaces",value:"No pinned spaces yet"},
    {key:"Directory",value:"DIRECTORY"},
    {key:"SearchSpaces",value:"Search spaces..."},
    {key:"AllSpaces",value:"All Spaces"},
    {key:"ItemsCount",value:"{count} items"},
    {key:"NoDescription",value:"No description"},
    {key:"CreateSpaceSuccess",value:"Space created successfully"},
    {key:"CreateSpaceFailed",value:"Failed to create space. Please try again."},
    {key:"SpaceOverview",value:"Space Overview"},
    {key:"Remaining",value:"Remaining"},
    {key:"CompletionRate",value:"Success Rate"},
    {key:"Done",value:"Done"},
    {key:"Overdue",value:"Overdue"},
    {key:"InProgress",value:"In Progress"},
    {key:"SpaceSettings",value:"Space Settings"},
    {key:"Workspace",value:"Workspace"},
    {key:"DangerZone",value:"Danger Zone"},
    {key:"DeleteSpace?",value:"Delete Space?"},
    {key:"DeleteSpaceConfirmation",value:"This action cannot be undone. All projects and tasks in this space will be permanently deleted."},
    {key:"SpaceDeletedSuccess",value:"Space deleted successfully"},
    {key:"EditSpaceInfo",value:"Edit Space Info"},
    {key:"AddMember",value:"Add Member"},
    {key:"EnterUsername",value:"Enter username"},
    {key:"MemberAddedSuccess",value:"Member added successfully"},
    {key:"FailedToAddMember",value:"Failed to add member"},
    {key:"EditSpaceTitle",value:"Edit Space"},
    {key:"UpdateSpaceSuccess",value:"Space updated successfully"},
    {key:"UpdateSpaceFailed",value:"Failed to update space"},
    {key:"ManageMembers",value:"Manage Members"},
    {key:"AggregatedAcrossAllProjects",value:"Aggregated across all projects"},
    {key:"InviteUser",value:"Invite User"}
];