module.exports =[
    {key:"Profile",value:"Thông tin của tôi"},
    {key:"ChangePassword",value:"Đổi mật khẩu"},
    {key:"Signout",value:"Đăng xuất"},
    {key:"EditAvatar",value:"Thay Avatar"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Ảnh đại diện sẽ tự động thay đổi"},
    {key:"UploadNewPhoto",value:"Tải ảnh mới"},
    {key:"Update",value:"Cập nhật"},
    {key:"PersonalInfomation",value:"Hồ sơ của tôi"},
    {key:"PersonalStatistics",value:"Thống kê cá nhân"},
    {key:"RecentNotifyReceived",value:"Thông báo nhận được gần đây"},
    {key:"ViewMore",value:"Xem thêm"},
    {key:"Collapse",value:"Thu gọn"},
    {key:"RecentInfomations",value:"Thông tin gần đây"},
    {key:"MySettings",value:"Cài đặt của tôi"},
    {key:"Tenants",value:"Tenants"},
    {key:"ProfileDescription",value:"Thông tin cá nhân và cài đặt bảo mật tài khoản."},
    {key:"Avatar",value:"Ảnh đại diện"},
    {key:"FullName",value:"Họ và tên"},
    {key:"Password",value:"Mật khẩu"},
    {key:"User",value:"Người dùng"},
    {key:"EmailAddress",value:"Địa chỉ email"},
    {key:"EmailCannotBeChanged",value:"Email không thể thay đổi sau khi xác minh"},
    {key:"EnterNewPassword",value:"Nhập mật khẩu mới"},
    {key:"AppearanceDescription",value:"Chọn chế độ sáng/tối hoặc tự động theo hệ thống."},
    {key:"Light",value:"Sáng"},
    {key:"Dark",value:"Tối"},
    {key:"SaveChanges",value:"Lưu thay đổi"},
    {key:"ProfileUpdatedSuccessfully",value:"Cập nhật hồ sơ thành công"},
    {key:"FailedToUpdateProfile",value:"Cập nhật hồ sơ thất bại"},
    {key:"PasswordManagedByGoogle",value:"Mật khẩu quản lý bởi Google"},
    {key:"PasswordManagedByGoogleDescription",value:"Tài khoản sử dụng Google, không thể đổi mật khẩu tại đây."},
    {key:"AllSettings",value:"Tất cả cài đặt"},
    {key:"People",value:"Mọi người"},
    {key:"General",value:"Chung"},
    {key:"Spaces",value:"Không gian"},
    {key:"LogOut",value:"Đăng xuất"},
    {key:"ProfileSettings",value:"Cài đặt hồ sơ"},
    {key:"MyTenants",value:"Tenants của tôi"},
    {key:"LoadingTenants",value:"Đang tải tenants..."},
    {key:"FreeForever",value:"Miễn phí mãi mãi"},
    {key:"Person",value:"người"},
    {key:"Settings",value:"Cài đặt"},
    {key:"Leave",value:"Rời khỏi"},
    {key:"ManagePeople",value:"Quản lý người dùng"},
    {key:"SearchOrInviteByEmail",value:"Tìm kiếm hoặc mời qua email"},
    {key:"InvitePeople",value:"Mời người dùng"},
    {key:"AllUsers",value:"Tất cả người dùng"},
    {key:"Owner",value:"Chủ sở hữu"},
    {key:"Admin",value:"Quản trị viên"},
    {key:"Member",value:"Thành viên"},
    {key:"Name",value:"Tên"},
    {key:"Email",value:"Email"},
    {key:"Role",value:"Vai trò"},
    {key:"Status",value:"Trạng thái"},
    {key:"LastActive",value:"Hoạt động lần cuối"},
    {key:"InvitedBy",value:"Được mời bởi"},
    {key:"InvitedOn",value:"Được mời vào"},
    {key:"NoMembersFound",value:"Không tìm thấy thành viên"},
    {key:"Today",value:"Hôm nay"},
    {key:"Yesterday",value:"Hôm qua"},
    {key:"DaysAgo",value:"{{count}} ngày trước"},
    {key:"ResendInvitation",value:"Gửi lại lời mời"},
    {key:"CancelInvite",value:"Hủy lời mời"},
    {key:"SetAsAdmin",value:"Đặt làm quản trị viên"},
    {key:"SetAsMember",value:"Đặt làm thành viên"},
    {key:"Remove",value:"Xóa"},
    {key:"GeneralSettings",value:"Cài đặt chung"},
    {key:"TenantInformation",value:"Thông tin Tenant"},
    {key:"TenantInformationDescriptionOwner",value:"Quản lý cài đặt chung. Chỉ chủ sở hữu mới có quyền chỉnh sửa."},
    {key:"TenantInformationDescriptionViewer",value:"Xem thông tin chung của tenant."},
    {key:"TenantAvatar",value:"Ảnh đại diện Tenant"},
    {key:"OnlyOwnerCanChangeTenantAvatar",value:"Chỉ chủ sở hữu mới có thể thay đổi ảnh đại diện"},
    {key:"TenantName",value:"Tên Tenant"},
    {key:"OnlyOwnerCanChangeTenantName",value:"Chỉ chủ sở hữu mới có thể thay đổi tên tenant"},
    {key:"Members",value:"Thành viên"},
    {key:"LoadingTenantInformation",value:"Đang tải thông tin tenant..."},
    {key:"NewSpace",value:"Không gian mới"},
    {key:"LoadingSpaces",value:"Đang tải không gian..."},
    {key:"NoSpacesFound",value:"Không tìm thấy không gian"},
    {key:"NoSpacesYet",value:"Chưa có không gian nào"},
    {key:"Space",value:"Không gian"},
    {key:"Visibility",value:"Hiển thị"},
    {key:"SharedWith",value:"Chia sẻ với"},
    {key:"GoToSpace",value:"Đi đến không gian"},
    {key:"Private",value:"Riêng tư"},
    {key:"Public",value:"Công khai"},
    {key:"OnlyInvitedMembers",value:"Chỉ thành viên được mời"},
    {key:"Everyone",value:"Mọi người"},
    {key:"Share",value:"Chia sẻ"},
    {key:"MakePrivate",value:"Đặt riêng tư"},
    {key:"ThisSectionComingSoon",value:"Phần này sắp ra mắt."},
    {key:"RemoveMember",value:"Xóa thành viên"},
    {key:"RemoveMemberConfirmMessage",value:"Bạn có chắc chắn muốn xóa {{name}}? Hành động này không thể hoàn tác."},
    {key:"ThisMember",value:"thành viên này"},
    {key:"Cancel",value:"Hủy"},
    {key:"Saving",value:"Đang lưu..."},
    {key:"InvitationResentSuccessfully",value:"Gửi lại lời mời thành công"},
    {key:"ResendFailed",value:"Gửi lại thất bại"},
    {key:"CanceledInvite",value:"Đã hủy lời mời"},
    {key:"CancelFailed",value:"Hủy thất bại"},
    {key:"TenantIdMissing",value:"Thiếu ID Tenant"},
    {key:"MemberUsernameMissing",value:"Thiếu tên người dùng thành viên"},
    {key:"ServiceMethodNotAvailable",value:"Phương thức không khả dụng. Vui lòng tải lại trang."},
    {key:"MemberRoleUpdatedToAdmin",value:"Cập nhật thành quản trị viên thành công"},
    {key:"MemberRoleUpdatedToMember",value:"Cập nhật thành thành viên thành công"},
    {key:"FailedToSetAsAdmin",value:"Cập nhật quản trị viên thất bại"},
    {key:"FailedToSetAsMember",value:"Cập nhật thành viên thất bại"},
    {key:"AvatarUploadComingSoon",value:"Tải ảnh đại diện sắp ra mắt"},
    {key:"TenantUpdatedSuccessfully",value:"Cập nhật tenant thành công"},
    {key:"FailedToUpdateTenant",value:"Cập nhật tenant thất bại"},
    {key:"MemberRemovedSuccessfully",value:"Xóa thành viên thành công"},
    {key:"FailedToRemoveMember",value:"Xóa thành viên thất bại"},
    {key:"FailedToLoadSpaces",value:"Không thể tải không gian"},
    {key:"FailedToLoadWorkspaces",value:"Không thể tải workspaces"},
    {key:"FailedToLoadMembers",value:"Không thể tải thành viên"},
    {key:"AvatarUploadedSuccessfully",value:"Tải ảnh đại diện thành công"},
    {key:"FailedToUploadAvatar",value:"Không thể tải ảnh đại diện"},
    {key:"EditProfile",value:"Chỉnh sửa hồ sơ"},
    {key:"NotificationSettings",value:"Cài đặt thông báo"},
    {key:"InviteUsers",value:"Mời người dùng"},
    {key:"HelpAndResources",value:"Trợ giúp & Tài nguyên"},
    {key:"Online",value:"Trực tuyến"},
    {key:"EmailCopied",value:"Sao chép email thành công"},
    {key:"Teams",value:"Nhóm"},
    {key:"MuteNotifications",value:"Tắt tiếng thông báo"},
    {key:"NotificationsMuted",value:"Đã tắt tiếng thông báo"},
    {key:"NotificationsUnmuted",value:"Đã bật tiếng thông báo"},
    {key:"NameCannotBeEmpty",value:"Tên không được để trống"},
    {key:"UpdateProfileSuccess",value:"Cập nhật hồ sơ thành công"},
    {key:"UpdateProfileFailed",value:"Cập nhật hồ sơ thất bại"},
    {key:"App",value:"Ứng dụng"},
    {key:"Account",value:"Tài khoản"},
    {key:"DefaultLaunchPage",value:"Trang mặc định"},
    {key:"Sound",value:"Âm thanh"},
    {key:"ResetPassword",value:"Đặt lại mật khẩu"},
    {key:"DeleteAccount",value:"Xóa tài khoản"},
    {key:"LightMode",value:"Chế độ sáng"},
    {key:"DarkMode",value:"Chế độ tối"},
    {key:"SystemMode",value:"Theo hệ thống"},
    {key:"WelcomeBack",value:"Chào mừng trở lại"},
    {key:"GoodMorning",value:"Chào buổi sáng"},
    {key:"GoodAfternoon",value:"Chào buổi chiều"},
    {key:"GoodEvening",value:"Chào buổi tối"},
    {key:"GoodNight",value:"Chúc ngủ ngon"},
    {key:"MyWorkspace",value:"Workspace của tôi"},
    {key:"MarkAllRead",value:"Đánh dấu tất cả đã đọc"},
    {key:"CreateNew",value:"Tạo mới"},
    {key:"CreateSpaceDesc",value:"Tạo không gian làm việc cho nhóm hoặc bộ phận."},
    {key:"CreateProjectDesc",value:"Sắp xếp các dự án vào một lộ trình chung."},
    {key:"CreateTaskDesc",value:"Tạo một nhiệm vụ mới được giao."},
    {key:"MySpaces",value:"Không gian của tôi"},
    {key:"PendingTasks",value:"Nhiệm vụ đang chờ"},
    {key:"NoPendingTasks",value:"Không có nhiệm vụ nào đang chờ"},
    {key:"TaskProgress",value:"Tiến độ nhiệm vụ"},
    {key:"InProgress",value:"Đang thực hiện"},
    {key:"Tasks",value:"Nhiệm vụ"},
    {key:"CouldNotLoadTasks",value:"Không thể tải danh sách nhiệm vụ"},
    {key:"Retry",value:"Thử lại"},
    {key:"NoTasksFound",value:"Không tìm thấy nhiệm vụ nào"},
    {key:"Search",value:"Tìm kiếm"},
    {key:"AnonymousUser",value:"Người dùng ẩn danh"},
    {key:"Notifications",value:"Thông báo"},
    {key:"WorkspaceOverview",value:"Tổng quan workspace"},
    {key:"Home",value:"Trang chủ"},
    {key:"Chat",value:"Trò chuyện"},
    {key:"Docs",value:"Tài liệu"},
    {key:"Planner",value:"Kế hoạch"},
    {key:"Projects",value:"Dự án"},
    {key:"ResetPasswordDescription",value:"Vì bảo mật, vui lòng truy cập website để đặt lại mật khẩu."},
    {key:"GoToWebsite",value:"Đi đến trang web"},
    {key:"BackToSignIn",value:"Quay lại đăng nhập"},
    {key:"DeleteAccountConfirmation",value:"Bạn chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác."},
    {key:"Delete",value:"Xóa"},
    {key:"MasterControl",value:"Điều khiển chung"},
    {key:"MuteAll",value:"Tắt tất cả"},
    {key:"MuteAllDescription",value:"Tắt tất cả thông báo ngay lập tức"},
    {key:"SoundDescription",value:"Phát âm thanh khi có cảnh báo"},
    {key:"ActivityAlerts",value:"Cảnh báo hoạt động"},
    {key:"NotifyAssigned",value:"Nhiệm vụ được giao"},
    {key:"NotifyAssignedDesc",value:"Nhận thông báo khi có nhiệm vụ mới được giao"},
    {key:"NotifyComment",value:"Bình luận & Nhắc tên"},
    {key:"NotifyCommentDesc",value:"Nhận thông báo khi có bình luận hoặc nhắc tên"},
    {key:"NotifyDeadline",value:"Nhắc nhở hạn chót"},
    {key:"NotifyDeadlineDesc",value:"Nhận thông báo về các hạn chót sắp tới"},
    {key:"Channels",value:"Kênh thông báo"},
    {key:"EmailNotifications",value:"Thông báo qua email"},
    {key:"EmailNotificationsDesc",value:"Nhận bản tóm tắt hoạt động hàng ngày"},
    {key:"SupportHub",value:"Trung tâm hỗ trợ"},
    {key:"HelpCenter",value:"Trung tâm trợ giúp"},
    {key:"HelpCenterDesc",value:"Các bài viết và hướng dẫn"},
    {key:"ContactSupport",value:"Liên hệ hỗ trợ"},
    {key:"ContactSupportDesc",value:"Nhận hỗ trợ từ đội ngũ của chúng tôi"},
    {key:"Community",value:"Cộng đồng"},
    {key:"CommunityDesc",value:"Tham gia máy chủ Discord của chúng tôi"},
    {key:"LegalPrivacy",value:"Pháp lý & Quyền riêng tư"},
    {key:"PrivacyPolicy",value:"Chính sách bảo mật"},
    {key:"PrivacyPolicyDesc",value:"Cách chúng tôi xử lý dữ liệu"},
    {key:"TermsOfService",value:"Điều khoản dịch vụ"},
    {key:"TermsOfServiceDesc",value:"Quy tắc sử dụng dịch vụ"},
    {key:"Licenses",value:"Giấy phép nguồn mở"},
    {key:"LicensesDesc",value:"Vinh danh phần mềm bên thứ ba"},
    {key:"Version",value:"Phiên bản"},
    {key:"Build",value:"Bản dựng"},
    {key:"TasksCompletedCount",value:"{completed} trên {total} nhiệm vụ hoàn thành"},
    {key:"OverviewLabel",value:"TỔNG QUAN"},
    {key:"TodaysTasks",value:"NHIỆM VỤ HÔM NAY"},
    {key:"ActiveTasks",value:"Nhiệm vụ đang hoạt động"},
    {key:"OverdueCaps",value:"QUÁ HẠN"},
    {key:"CompletedCaps",value:"HOÀN THÀNH"},
    {key:"SeeAll",value:"XEM TẤT CẢ"},
    {key:"QuickAlerts",value:"Thông báo nhanh"},
    {key:"RecentSpaces",value:"Không gian gần đây"},
    {key:"LatestProjects",value:"Dự án mới nhất"},
    {key:"ConnectionError",value:"Lỗi kết nối"},
    {key:"ProjectsCount",value:"{count} Dự án"},
    {key:"AlertSarahUpdate",value:"Sarah đã cập nhật \"Lộ trình Q4\""},
    {key:"AlertDeadlineDocs",value:"Sắp đến hạn: \"Tài liệu API\""},
    {key:"MinutesAgo",value:"{count} phút trước"},
    {key:"HoursAgo",value:"{count} giờ trước"},
    {key:"NewVenture",value:"Dự án mới"},
    {key:"NoRecentActivity",value:"Chưa có hoạt động gần đây"},
    {key:"NoProjectsFound",value:"Không tìm thấy dự án nào"},
    {key:"TasksCount",value:"{count} Nhiệm vụ"},
    {key:"PinnedSpaces",value:"Không gian đã ghim"},
    {key:"NoPinnedSpaces",value:"Chưa có spaces nào được ghim"},
    {key:"Directory",value:"THƯ MỤC"},
    {key:"SearchSpaces",value:"Tìm kiếm không gian..."},
    {key:"AllSpaces",value:"Tất cả không gian"},
    {key:"ItemsCount",value:"{count} mục"},
    {key:"NoDescription",value:"Chưa có mô tả"},
    {key:"CreateSpaceSuccess",value:"Tạo không gian thành công"},
    {key:"CreateSpaceFailed",value:"Không thể tạo không gian. Vui lòng thử lại sau."},
    {key:"SpaceOverview",value:"Tổng quan không gian"},
    {key:"Remaining",value:"Còn lại"},
    {key:"CompletionRate",value:"Tỉ lệ hoàn thành"},
    {key:"Done",value:"Hoàn thành"},
    {key:"Overdue",value:"Quá hạn"},
    {key:"InProgress",value:"Đang thực hiện"},
    {key:"SpaceSettings",value:"Cài đặt không gian"},
    {key:"Workspace",value:"Không gian làm việc"},
    {key:"DangerZone",value:"Vùng nguy hiểm"},
    {key:"DeleteSpace?",value:"Xóa không gian này?"},
    {key:"DeleteSpaceConfirmation",value:"Hành động này không thể hoàn tác. Tất cả dự án và công việc trong không gian này sẽ bị xóa vĩnh viễn."},
    {key:"SpaceDeletedSuccess",value:"Xóa không gian thành công"},
    {key:"EditSpaceInfo",value:"Chỉnh sửa thông tin"},
    {key:"AddMember",value:"Thêm thành viên"},
    {key:"EnterUsername",value:"Nhập tên đăng nhập"},
    {key:"MemberAddedSuccess",value:"Thêm thành viên thành công"},
    {key:"FailedToAddMember",value:"Thêm thành viên thất bại"},
    {key:"EditSpaceTitle",value:"Chỉnh sửa không gian"},
    {key:"UpdateSpaceSuccess",value:"Cập nhật không gian thành công"},
    {key:"UpdateSpaceFailed",value:"Cập nhật không gian thất bại"},
    {key:"ManageMembers",value:"Quản lý thành viên"},
    {key:"AggregatedAcrossAllProjects",value:"Tổng hợp từ tất cả dự án"},
    {key:"ProjectInvitation",value:"Lời mời tham gia dự án"},
    {key:"InvitationSentSuccess",value:"Đã gửi thư mời đến Gmail thành công!"},
    {key:"FailedToSendInvitation",value:"Gửi lời mời thất bại. Vui lòng thử lại."},
    {key:"OnlyGmailAllowed",value:"Chỉ cho phép địa chỉ @gmail.com để mời thành viên."},
    {key:"EnterGmailInvite",value:"Nhập địa chỉ Gmail người nhận"},
    {key:"Pending",value:"Chờ"},
    {key:"AcceptingInvitation",value:"Đang tham gia cộng tác..."},
    {key:"InvitationAccepted",value:"Chào mừng bạn đến với không gian!"},
    {key:"AcceptFailed",value:"Không thể xác thực lời mời"},
    {key:"InviteUser",value:"Mời người dùng"}
];